### PR TITLE
Add an optional config to RenderConfig to allow for 3rd party libraries to hook into attr merging

### PR DESCRIPTION
**Pull request by busti**
This Pull Request adds a hook into `RenderConfig` which allows third party libraries to hook into attribute merging. 

This is especially useful for class names which can override each other, like those used by tailwind. 
This feature could for example be used with `tailwind-merge` as follows:  

```scala
import outwatch._
import outwatch.dsl._
import tailwindMerge._

val config = RenderConfig(
  errorModifier: _ => VMod.empty,  
  accumAttrHook => Some((attr, other) => if (attr.title == "class") twMerge(attr.value, other) else a.accum(attr.value, other)),
)

Outwatch.renderInto("#app", div(cls := "hidden", cls := "visible", config)
```

### CODE REVIEW

**Comment by cornerman** [comment]
@busti Sorry, just realized my review comment was pending the whole time and was not sent out :/

**Review by cornerman — APPROVED** [review]
Thank you. LGTM :+1:

**Comment by busti** [comment]
Had to rename the parameter since scalac was complaining that it was shadowing the `a` VNode from the dsl.

**Comment by busti** [comment]
For some reason the tests still fail though.

**Comment by busti** [comment]
Now just about everything fails. 
Also I apparently misinterpreted the error message from before.  
Problem is I cannot reproduce the original error locally.

**Pull request merged**
