### PR TITLE
use div instead of app as tag for Outwatch.renderInto

### LINKED ISSUE #223: Outwatch.renderInto() uses a common magic value
I had difficulty using `Outwatch.renderInto` so I eventually hacked a solution using `renderReplace`.  It turns out I was using an element id `"app"` and renderInto was creating one with the same id.

Perhaps the magic value "app" should get changed to something less likely to collide in the wild? 

```
  def renderInto(element: dom.Element, vNode: VNode)(implicit s: Scheduler): IO[Unit] = for {
    node <- vNode
    _ <- IO {
      val elem = dom.document.createElement("app")
      element.appendChild(elem)
      patch(elem, node.toSnabbdom)
    }
  } yield ()
```

### PR DESCRIPTION
**Pull request by cornerman**
fixes #223

### CODE REVIEW

**Comment by LukaJCB** [comment]
This test seems to fail:

```
should support emitter operations *** FAILED ***
```

**Comment by cornerman** [comment]
Interesting. This is because we are now patching one node with the same `sel` (both div). And now `patch` is called instead of `insert` by snabbdom. Before we were patching a tag `app` with a different tag `div`.

**Comment by cornerman** [comment]
I am working on new hooks `onDomMount`, `onDomUpdate`, `onDomUnmount`. These can reliably tell whether a node is newly inserted/patched or is just updated. So when using these hooks, we can fix the tests.

**Comment by cornerman** [comment]
Fixed the tests for now by ensuring keys on the relevant inserted nodes.

**Pull request merged**
