### PR TITLE
Update to Scala.js 1.8.0

### PR DESCRIPTION
**Pull request by armanbilge**
Supersedes https://github.com/outwatch/outwatch/pull/551. This should hopefully get you unblocked while we wait for https://github.com/scalameta/mdoc/pull/597.

### CODE REVIEW

**Comment by fdietze** [comment]
Awesome, thank you!

**Comment by fdietze** [comment]
Strange... After merging, CI is failing on master now, any ideas how to fix it?

https://github.com/outwatch/outwatch/runs/4747821013?check_suite_focus=true

`scala-dom-types` was updated right before the change.

**Comment by armanbilge** [comment]
Actually, I thought it was strange that your project didn't have that problem, since mine did 😅 That is problem (3) from this issue that I wrote up:
- https://github.com/scalameta/mdoc/issues/601

It's all very broken and confusing, sorry about that. I think I know how to fix, let me give it a try.

**Comment by armanbilge** [comment]
@fdietze fix in https://github.com/outwatch/outwatch/pull/564.

**Pull request merged**
