### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fdietze**

### CODE REVIEW

**Comment by LukaJCB** [comment]
Dependcy upgrades look good to me, though there seems to be some unrelated things as well

**Comment by fdietze** [comment]
The changes in `DomTypes.scala` are needed for the dom-types upgrade. Or which changes do you mean?

**Comment by LukaJCB** [comment]
The renaming is part of the upgrade then? If so, :+1:

**Comment by fdietze** [comment]
yes, the update separated html and svg tags. So we renamed the traits to be consistent.

**Comment by LukaJCB** [comment]
:+1:

**Comment by fdietze** [comment]
@LukaJCB Is anything missing, or did you just forget to approve? :wink:

**Pull request merged**
