### PR TITLE
Upgrade scalajs dependency and readme references

### PR DESCRIPTION
**Pull request by zakpatterson**
Just started to try out this library today, trying to help out with any bumps I run into.

### CODE REVIEW

**Comment by fdietze** [comment]
Thank you for doing this!

I think there was a problem with `scala-js-bundler` `0.14.0`. It had to do with loading the custom javascript file in this repo. Is it working for you?

**Comment by fdietze** [comment]
And feel free to ask any questions you have on Gitter: https://gitter.im/OutWatch/Lobby

**Comment by zakpatterson** [comment]
It's true, given these plugins:
```
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.14.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.26")
```
and this most recent commit dependency for outwatch,
```
      "io.github.outwatch" % "outwatch" % "ea240c6d04",
```
I'm getting an error loading that snabbdom props file, whereas I'm not getting it with "sbt-scalajs-bundler" % "0.13.1". Here's the output I'm seeing for reference:

```
[info] Fast optimizing /projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/myproject-frontend-fastopt.js
[error] yarn install v1.13.0
[error] [1/4] Resolving packages...
[error] [2/4] Fetching packages...
[error] [3/4] Linking dependencies...
[error] [4/4] Building fresh packages...
[error] Done in 7.69s.
[info] Writing module entry point for myproject-frontend-fastopt-entrypoint.js
[info] Building webpack library bundles for myproject-frontend-fastopt in /projdir/server/frontend/target/streams/$global/$global/$global/streams/fastOptJS-webpack-libraries
[info] Writing scalajs.webpack.config.js
[error] ModuleNotFoundError: Module not found: Error: Can't resolve './snabbdom-custom-props' in '/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main'
[error]     at factory.create (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/webpack/lib/Compilation.js:796:10)
[error]     at factory (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
[error]     at resolver (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
[error]     at asyncLib.parallel (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
[error]     at /projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/neo-async/async.js:2825:7
[error]     at /projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/neo-async/async.js:6886:13
[error]     at normalResolver.resolve (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
[error]     at doResolve (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
[error]     at hook.callAsync (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
[error]     at _fn0 (eval at create (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
[error]     at resolver.doResolve (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
[error]     at hook.callAsync (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
[error]     at _fn0 (eval at create (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
[error]     at hook.callAsync (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
[error]     at _fn0 (eval at create (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
[error]     at resolver.doResolve (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
[error]     at hook.callAsync (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
[error]     at _fn42 (eval at create (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:393:1)
[error]     at hook.callAsync (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
[error]     at _fn0 (eval at create (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
[error]     at resolver.doResolve (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
[error]     at hook.callAsync (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
[error]     at _fn1 (eval at create (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
[error]     at hook.callAsync (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
[error]     at _fn0 (eval at create (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
[error]     at fs.stat (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)
[error]     at process.nextTick (/projdir/server/frontend/target/scala-2.12/scalajs-bundler/main/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
[error]     at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

**Comment by zakpatterson** [comment]
These versions are in master now, so I'll close.

**Pull request closed without merging**
