### PR TITLE
add EmitterBuilder.combine

### PR DESCRIPTION
**Pull request by cornerman**

### CODE REVIEW

**Comment by LukaJCB** [comment]
Do we have a `Monoid` on our hands? :)

**Comment by cornerman** [comment]
> Do we have a Monoid on our hands? :)

Oh yes, good idea for VDomModifier and EmitterBuilder.

**Comment by cornerman** [comment]
There are even more typeclasses like monads and functors, we should really add for some outwatch types that we currently lack. I have some defined in my app, but I need some time to put them in a PR.

**Comment by cornerman** [comment]
@LukaJCB I have updated the PR to add `Monoid` instances for `VDomModifier` and `EmitterBuilder` as well as adding `Functor` and `Bifunctor` for `EmitterBuilder`.

**Pull request merged**
