### PR TITLE
Library Helpers for Javascript Libraries

### PR DESCRIPTION
**Pull request by cornerman**
This PR adds helpers for javascript libraries:

- hammer-js
- clipboard-js
- *more to come*

I would like to add more that I already have implemented in my own projects. Just unsure whether this should live in this repository or in another repository. What do you all think?

### CODE REVIEW

**Comment by busti** [comment]
I personally feel like this should live in a different repo. 
I'd go so far as to say that there should be a separate artifact for every supported js library, maybe even a separate repo each.

**Comment by cornerman** [comment]
Yeah agree, we definitely need a separate artifact for each adapter library. I was a bit lazy but you are probably rightabout a different repo. I will make an outwatch-libs repo, where i will put all of them for now. We can think about whether there should be multiple repos :)

**Comment by busti** [comment]
Sounds good. I'd be happy to contribute some of my own helpers.

**Comment by cornerman** [comment]
Awesome! I have created a new repo (https://github.com/OutWatch/outwatch-libs) and will push these changes to it later.

**Pull request closed without merging**
