### PR TITLE
Make renderWithStore accept an IO[VNode] instead of VNode.

### PR DESCRIPTION
**Pull request by rfuerst87**
See discussion in #310.

### CODE REVIEW

**Comment by cornerman** [comment]
@rfuerst87 Thank you! LGTM, though I would like to have an overload of this method for `VNode` as well, because the rest of the methods accept only `VNode` - it feels a bit more consistent.

Can you add that?

**Comment by rfuerst87** [comment]
@cornerman Of course I can add an overload. Shall I add it to both classes (`Outwach` and `Store`)?

**Comment by cornerman** [comment]
@rfuerst87 Good question. Imho, the method in `OutWatch` should suffice, because all methods there accept a `VNode`. For the `Store`, it should be fine as is :)

**Comment by rfuerst87** [comment]
Sorry for the long delay. I was extra busy the past few days.

**Pull request merged**
