### PR TITLE
enable some scalac options and fix warnings

### PR DESCRIPTION
**Pull request by cornerman**

### CODE REVIEW

**Comment by LukaJCB** [comment]
Hi, can we also add `-Ypartial-unification`? :)

**Comment by cornerman** [comment]
sure :)

**Comment by LukaJCB** [comment]
And also fix some the build on 2.11? :)

**Comment by cornerman** [comment]
ups, I did not check that. should be working for both now.

**Comment by cornerman** [comment]
one test seems to be flaky, it already failed before here: https://travis-ci.org/OutWatch/outwatch/jobs/280875080#L1092

**Pull request merged**
