### PR TITLE
Use SBT 1.0

### PR DESCRIPTION
**Pull request by fdietze**

### CODE REVIEW

**Comment by fdietze** [comment]
@LukaJCB  Just rebased on master. After a successful test run, this can be merged.

**Comment by LukaJCB** [comment]
Thanks, I was going to do this, but it was really slow, probably due to https://github.com/sbt/sbt/issues/3527. So I'd rather wait until that is resolved.

**Comment by cornerman** [comment]
The new sbt version `1.0.3` now support falling back to polling watch-mode: https://github.com/sbt/sbt/releases/tag/v1.0.3

Maybe interesting for macos, an sbt plugin which enables a native file-watcher: https://www.reddit.com/r/scala/comments/79wcew/native_dropin_replacement_for_slow_sbt_10/

**Comment by fdietze** [comment]
Apple people, are there still any issues?

**Comment by LukaJCB** [comment]
Merging this :)

**Pull request merged**
