### PR TITLE
Link source maps to raw.githubusercontent.com

### PR DESCRIPTION
**Pull request by fdietze**
I saw this interesting snippet in [build.sbt](https://github.com/lihaoyi/scala.rx/blob/master/build.sbt#L57) and thought , that it might be useful for debugging. But I wasn't able to verify that its working.

### CODE REVIEW

**Comment by mariusmuja** [comment]
Nice! But I think it should be:
```diff
-  val a = baseDirectory.value.toURI.toString.replaceFirst("[^/]+/?$", "")
+  val a = baseDirectory.value.toURI
```

**Comment by fdietze** [comment]
I cannot find any relevant url in the source-map files. I think this is for source-maps from scalaJS itself, but bundler does not adopt it yet.

**Comment by mariusmuja** [comment]
The urls are in the `.sjsir` files and I verified that the bundler includes them in the `.map` files.

**Comment by fdietze** [comment]
I now included the current git hash in the URL, which should always load the correct source file.
I tested this successfully with chromium, which now shows the source file when debugging.

Try it with this dependency:

```scala
"com.github.fdietze" % "outwatch" % "3f5cd8e"
```

I suggest that other libraries use this approach as well.

**Pull request merged**
